---

mongodb_package: mongodb-org
mongodb_version: "3.2"

mongodb_security_authorization: "enabled"

mongodb_user_admin_name: "siteUserAdmin"
mongodb_user_admin_password: "passw0rd"

mongodb_root_admin_name: "siteRootAdmin"
mongodb_root_admin_password: "passw0rd"

mongodb_root_backup_name: "backupuser"
mongodb_root_backup_password: "passw0rd"

mongodb_users:
  - {
    name: "datahub",
    password: "datahub",
    roles: "dbAdmin",
    database: "admin"
}
