---

nginx_vhosts:
  - listen: "80"
    server_name: "datahub.box"
    root: "/vagrant/datahub/web"
    index: "index.php index.html index.htm"
#    error_page: ""
    access_log: "/var/log/nginx/project_access.log"
    error_log: "/var/log/nginx/project_error.log"
    extra_parameters: |
      location / {
          # try to serve file directly, fallback to app.php
          try_files $uri /app_dev.php$is_args$args;
      }

      # DEV
      # This rule should only be placed on your development environment
      # In production, don't include this and don't deploy app_dev.php or config.php
      location ~ ^/(app_dev|config)\.php(/|$) {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;
          # When you are using symlinks to link the document root to the
          # current version of your application, you should pass the real
          # application path instead of the path to the symlink to PHP
          # FPM.
          # Otherwise, PHP's OPcache may not properly detect changes to
          # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
          # for more information).
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
      }

      # PROD
      location ~ ^/app\.php(/|$) {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;
          # When you are using symlinks to link the document root to the
          # current version of your application, you should pass the real
          # application path instead of the path to the symlink to PHP
          # FPM.
          # Otherwise, PHP's OPcache may not properly detect changes to
          # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
          # for more information).
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
          # Prevents URIs that include the front controller. This will 404:
          # http://domain.tld/app.php/some-path
          # Remove the internal directive to allow URIs like this
          internal;
      }

      # return 404 for all other php files not matching the front controller
      # this prevents access to other php files you don't want to be accessible.
      location ~ \.php$ {
        return 404;
      }

  - listen: "80"
    server_name: "blacklight.box"
#    root: "/vagrant/project-blacklight"
#    index: "index.php index.html index.htm"
#    error_page: ""
    access_log: "/var/log/nginx/blacklight_project_access.log"
    error_log: "/var/log/nginx/blacklight_project_error.log"
    extra_parameters: |
        passenger_enabled on;
        passenger_app_env development;
        root /vagrant/project-blacklight/public;

  - listen: "80"
    server_name: "xhprof.box"
    root: "/usr/share/php/xhprof_html/"
    index: "index.php index.html index.htm"
    access_log: "/var/log/nginx/xhprof_project_access.log"
    error_log: "/var/log/nginx/xhprof_project_error.log"
    extra_parameters: |
        location / {
          index index.php;
        }

        location ~ ^/(index|callgraph)\.php(/|$) {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 8 128k;
            fastcgi_index index.php;
        }
