---
php_webserver_daemon: "nginx"
php_enable_php_fpm: true

php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/cli/conf.d

php_fpm_daemon: php7.0-fpm

php_display_errors: "On"
php_display_startup_errors: "On"
