---
- name: Install Catmandu Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - make
    - libmodule-install-perl
    - libyaz-dev
    - libwrap0-dev
    - libxml2-dev
    - zlib1g
    - zlib1g-dev
    - libexpat1-dev
    - libxslt1-dev
    - libssl-dev
    - libgdbm-dev
    - perl-doc

- shell: yes | cpan Test::More
- shell: yes | cpan YAML
- shell: yes | cpan App::cpanminus
- shell: /usr/local/bin/cpanm Catmandu Catmandu::LIDO
